name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        
    - run: go test -v -race ./...
    
    - run: |
        go mod tidy
        git diff --exit-code go.mod go.sum
    
    - run: go vet ./...
    
    - uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: --timeout=5m
